[package]
name        = "kickmessvst"
version     = "0.1.0"
authors     = ["Weird Constructor <weirdconstructor@gmail.com>"]
edition     = "2018"
license     = "GPL-3.0-or-later"
description = "Kickmess - Port of LMMS Kicker Plugin"

[lib]
name       = "kickmessvst"
crate-type = ["cdylib", "lib"]

[dependencies]
vst                = { git = "https://github.com/rustaudio/vst-rs" }
cairo-rs           = "0.9.1"
raw-window-handle  = "0.3"
cairo-sys-rs       = { version = "0.10.0", features=["xlib"] }
x11                = { version = "2.18.2" }

#baseview           = { git = "https://github.com/RustAudio/baseview.git" }
baseview           = { path = "/home/weictr/devel/other/baseview" }

pugl-sys           = { git = "https://github.com/johannes-mueller/pugl-sys.git" }
#pugl-sys           = { path = "/home/weictr/devel/other/pugl-sys/" }

gl                 = "0.14.0"
glutin             = "0.24.1"
femtovg            = { git = "https://github.com/femtovg/femtovg" }
raw-gl-context     = { git = "https://github.com/glowcoil/raw-gl-context" }

[dev-dependencies]
winit = "0.22.2"
