[package]
name    = "kickmess"
version = "0.1.0"
authors = ["Weird Constructor <weirdconstructor@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "Kickmess - Port of LMMS Kicker Plugin for LV2"

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2                = { version = "0.6.0" }
wlambda            = { path = "../wlambda" }
wctr_signal_ops    = { path = "../wctr-signal-ops" }

[dev-dependencies]
ggez               = "0.5.1"
# vecmath            = "1.0.0"
# nalgebra           = "0.18.0"
# mint               = "0.5.1"
