name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
  
        
    steps:
    - uses: actions/checkout@v2  
    
    
    #odn't ask me why because it's a reason i think build fails
    - name: Install Xorg 
      run: |
          sudo apt update
          sudo apt-get install xserver-xorg-core --no-install-recommends --no-install-suggests
    
    - name: Enable caching
      uses: Swatinem/rust-cache@v1.3.0
    
    - name: Build
      run: cargo build --all-features --release --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Upload Artifact Linux
      uses: actions/upload-artifact@v2.2.4
      with:
        name: linux
        path: target/release/libkickmessvst.so
      
      
