name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
  
        
    steps:
    - uses: actions/checkout@v2  
    
    
    - name: Install dependencies 
      run: |
          sudo apt-get update
          sudo apt-get install xorg xorg-dev gcc  libx11-dev libxcursor-dev libxcb-dri2-0-dev libxcb-icccm4-dev libx11-xcb-dev libxcb-icccm4 libx11-xcb1 libx11-xcb-dev libxcb-dri2-0 libxcb-dri2-0-dev -y
    
    - name: Enable caching
      uses: Swatinem/rust-cache@v1.3.0
    
    - name: Build
      run: cargo build --all-features --release --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Upload Artifact Linux
      uses: actions/upload-artifact@v2.2.4
      with:
        name: linux
        path: target/release/libkickmessvst.so
      
      
